notes = [
        	{
                title: "Geometria A - mod 1",
                date: "29/11/22",
                text: "Appunti del corso di Geometria A - mod 1 tenuto dal prof. L.E. Sola Conde",
                link: "https://davideborra.notion.site/Geometria-A-f587dd8f407f40cf8c3097028891a791",
                linkText: "Geometria A",
                topic: "Geometria",
                school: "Uni",
                showDetails: false,
                show: true,
            },
            {
                title: "Analisi Matematica A - mod 1",
                date: "9/12/22",
                text: "Trascrizioni delle esercitazioni di Analisi tenute da S. Vercellesi",
                link: "https://github.com/dborra03/esercitazione-analisi-A-2022-23",
                linkText: "Analisi A - GitHub",
                topic: "Analisi",
                school: "Uni",
                showDetails: false,
                show: true,
            },
            {
                title: "Funzioni ℝ → ℝ",
                date: "26/12/22",
                text: "Riassunto prodotto da me.",
                link: "https://github.com/davideborra/appunti-liceo/raw/main/funzioni/main.pdf",
                linkText: "Funzioni",
                topic: "Analisi",
                school: "Liceo",
                showDetails: false,
                show: true,
            },
            {
                title: "Fisica gen. 1 - mod 1",
                date: "17/01/23",
                text: "Note prodotte in preparazione all'esame basate sul materiale fornito dalla prof.ssa Dolesi",
                link: "https://github.com/davideborra/appunti-uni/raw/main/Fisica-generale-1-(mod1)/main.pdf",
                linkText: "Fisica",
                topic: "Fisica",
                school: "Uni",
                showDetails: false,
                show: true,
            },
            {
                title: "Combinatoria e calcolo delle probabilità",
                date: "21/01/23",
                text: "Riassunto prodotto da me.",
                link: "https://github.com/davideborra/appunti-liceo/raw/main/combinatoria-e-cdp/main.pdf",
                linkText: "Combinatoria e CDP",
                topic: "Combinatoria e probabilità",
                school: "Liceo",
                showDetails: false,
                show: true,
            },
            {
                title: "Algebra lineare e successioni",
                date: "06/02/23",
                text: "Lezione per la Squadra di Matematica del Galilei",
                link: "https://github.com/davideborra/appunti-liceo/raw/main/alg-lineare-fibonacci/main.pdf",
                linkText: "Algebra lineare e Fibonacci",
                topic: "Geometria",
                school: "Liceo",
                showDetails: false,
                show: true,
            },
            {
                title: "Analisi 1",
                date: "02/03/23",
                text: "Revisione e ampliamento degli appunti del programma di quinta liceo",
                link: "https://github.com/davideborra/appunti-liceo/raw/main/analisi-1/main.pdf",
                linkText: "Analisi 1",
                topic: "Analisi",
                school: "Liceo",
                showDetails: false,
                show: true,
            },{
                title: "Geometria A - mod 2",
                date: "04/04/23",
                text: "Appunti del corso di Geometria A - mod 1 tenuto dal prof. M. Andreatta",
                link: "https://github.com/davideborra/appunti-uni/raw/main/Geometria-A-(mod2)%20/main.pdf",
                linkText: "Geometria A",
                topic: "Geometria",
                school: "Uni",
                showDetails: false,
                show: true,
            },{
                title: "Algebra A - Provetta",
                date: "06/06/23",
                text: "Esercizi del corso di Algebra A in preparazione alla seconda prova intermedia",
                link: "https://github.com/davideborra/appunti-uni/raw/main/provetta-algebra/spi%20algebra%20-%20soluzioni.pdf",
                linkText: "Geometria A",
                topic: "Geometria",
                school: "Uni",
                showDetails: false,
                show: true,
            }
        ];
