notes = [
            {
                title: "Lezioni Galilei",
                date: "",
                text: "Materiale per le lezioni che ho preparato per la Squadra di Matematica del Galilei.",
                link: "galilei",
                linkText: "Pagina del Sito dedicata",
                topic: "0",
                school: "Liceo",
                showDetails: false,
                show: true
            },    
        	{
                title: "Geometria A - mod 1",
                date: "29/11/22",
                text: "Appunti del corso di Geometria A - mod 1 tenuto dal prof. L.E. Sola Conde",
                link: "https://davideborra.notion.site/Geometria-A-f587dd8f407f40cf8c3097028891a791",
                linkText: "Geometria A",
                topic: "Geometria",
                school: "Uni",
                showDetails: false,
                show: true,
            },
            {
                title: "Analisi Mat. A - mod 1",
                date: "9/12/22",
                text: "Trascrizioni delle esercitazioni di Analisi tenute da S. Vercellesi",
                link: "https://github.com/davideborra/esercitazione-analisi-A-2022-23",
                linkText: "Analisi A - GitHub",
                topic: "Analisi",
                school: "Uni",
                showDetails: false,
                show: true,
            },
            {
                title: "Funzioni ℝ → ℝ",
                date: "26/12/22",
                text: "Riassunto prodotto da me.",
                link: "https://github.com/davideborra/appunti-liceo/raw/main/funzioni/main.pdf",
                linkText: "Funzioni",
                topic: "Analisi",
                school: "Liceo",
                showDetails: false,
                show: true,
            },
            {
                title: "Geometria Analitica nello Spazio",
                date: "26/12/22",
                text: "Riassunto prodotto da me.",
                link: "https://github.com/davideborra/appunti-liceo/raw/main/analitica-3d/main.pdf",
                linkText: "Analitica 3D",
                topic: "Geometria",
                school: "Liceo",
                showDetails: false,
                show: true,
            },
            {
                title: "Combinatoria e calcolo delle probabilità",
                date: "21/01/23",
                text: "Riassunto prodotto da me.",
                link: "https://github.com/davideborra/appunti-liceo/raw/main/combinatoria-e-cdp/main.pdf",
                linkText: "Combinatoria e CDP",
                topic: "Combinatoria e probabilità",
                school: "Liceo",
                showDetails: false,
                show: true,
            },
            {
                title: "Analisi 1",
                date: "02/03/23",
                text: "Revisione e ampliamento degli appunti del programma di quinta liceo",
                link: "https://github.com/davideborra/appunti-liceo/raw/main/analisi-1/main.pdf",
                linkText: "Analisi 1",
                topic: "Analisi",
                school: "Liceo",
                showDetails: false,
                show: true,
            }
        ];
